worlds:
    edb:
    - ECDK1OXZA
    - MAJEPK1DK
    - 46V6Z7N7T
    new world:
    - V9X1S7VCY
    ee3ee:
    - 17MEAQL2E
    - OGZMCTEJK
    - H3T3YBQYO
    - T9E4LR4G8
    - QAN3Y43VS
    world:
    - VFLVYJ1XB
    - UBRK3XNYP
    - RLGO3DOEA
    - 93TSUC28D
    - QWMO0RG3Y
    - A66E81RPK
    - BF5LAH2Q8
    - YJNC3WIT6
    - WX2MP5MKT
    - QAEJIKMCS
    - 4Z5QXLFNW
    - MWXICERBG
    - FNCBZ4ZXZ
    - ARS6HBJ22
