worlds:
    edb:
    - ECDK1OXZA
    - MAJEPK1DK
    - 46V6Z7N7T
    new world:
    - V9X1S7VCY
    ee3ee:
    - 17MEAQL2E
    - OGZMCTEJK
    - H3T3YBQYO
    - T9E4LR4G8
    - QAN3Y43VS
    world:
    - BF5LAH2Q8
    - MWXICERBG
    - A66E81RPK
