worlds:
    edb:
    - ECDK1OXZA
    - MAJEPK1DK
    - 46V6Z7N7T
    new world:
    - V9X1S7VCY
    ee3ee:
    - 17MEAQL2E
    - OGZMCTEJK
    - H3T3YBQYO
    - T9E4LR4G8
    - QAN3Y43VS
    world:
    - VFLVYJ1XB
    - UBRK3XNYP
    - RLGO3DOEA
    - 93TSUC28D
    - QWMO0RG3Y
    - 6OWNU5IWK
    - Q2NGTKTHY
    - N1VI6X4GD
    - A66E81RPK
    - GOH7E3NOA
    - FIAV30Z4X
    - OSBYIZKNV
    - BF5LAH2Q8
    - WX2MP5MKT
    - Q3OGSITLF
    - QAEJIKMCS
    - 4Z5QXLFNW
    - DGWWPU9RU
    - MWXICERBG
    - FNCBZ4ZXZ
    - ARS6HBJ22
    - HWDH7ARIE
    avp:
    - 58UMNCCU2
