worlds:
    edb:
    - ECDK1OXZA
    - MAJEPK1DK
    - 46V6Z7N7T
    new world:
    - V9X1S7VCY
    ee3ee:
    - 17MEAQL2E
    - OGZMCTEJK
    - H3T3YBQYO
    - T9E4LR4G8
    - QAN3Y43VS
    world:
    - ABKM2LL2M
    - VFLVYJ1XB
    - UBRK3XNYP
    - TYZQRUP2T
    - YA3HVAW6O
    - CXVJCMU4Y
    - YIW5ZTSTW
    - EAMSV6961
    - A66E81RPK
    - GHBK9LFEC
    - FIAV30Z4X
    - BF5LAH2Q8
    - WST9IRXLM
    - 7991GVPQF
    - QAEJIKMCS
    - DISTRS5XI
    - W8NT2C8WM
    - 4Z5QXLFNW
    - MWXICERBG
    - E5C9D1WDT
    - RLGO3DOEA
    - 93TSUC28D
    - 8HFA2INW6
    - QWMO0RG3Y
    - 4BQW06P8G
    - 6OWNU5IWK
    - Q2NGTKTHY
    - N1VI6X4GD
    - GOH7E3NOA
    - 7QBDXCLZ8
    - OSBYIZKNV
    - M35F7YLX2
    - WX2MP5MKT
    - L8E2CXCL6
    - Q3OGSITLF
    - DGWWPU9RU
    - Z2MZ2QI4L
    - H6QQVHA6L
    - FNCBZ4ZXZ
    - 2CIHVJUR5
    - ARS6HBJ22
    - P5M57ICT7
    - HWDH7ARIE
    - 6ZIGSXQWI
    avp:
    - KSSMPI3EU
    - 58UMNCCU2
    mining:
    - 6W7WD5MR6
    - G7D2DTF7U
